"""Canonical spectrum Profile API for serialized spectrum-access/v2 documents."""

from spectrum_profiles.v2.context import (
    active_profile_id,
    canonical_profile_json,
    canonical_profile_v2_json,
    get_active_profile_document,
    primary_spectrum_range,
    profile_context_from_document,
    profile_context_from_v2,
    profile_hash,
    profile_hash_v2,
    reload_active_profile_document,
    set_active_profile_document,
)
from spectrum_profiles.selection import DEFAULT_PROFILE_ID
from spectrum_profiles.v2.doctor import (
    ProfileDoctorFinding,
    ProfileDoctorReport,
    diagnose_profile_v2,
    package_bootstrap_adapter_discovery,
    package_bootstrap_rf_discovery,
    render_profile_doctor_report,
    run_profile_doctor,
)
from spectrum_profiles.v2.negotiate import (
    adapters_satisfying_device_capabilities,
    adapters_satisfying_network_capabilities,
    negotiate_profile_plugins,
)
from spectrum_profiles.v2.parse import (
    load_profile,
    load_profile_document,
    load_profile_document_with_provenance,
    load_profile_v2,
    load_profile_v2_document,
    load_profile_v2_document_with_provenance,
    load_profile_v2_with_provenance,
    load_profile_with_provenance,
    parse_profile_document,
    parse_profile_v2_spectrum,
)
from spectrum_profiles.v2.semantics import validate_profile_v2_semantics
from spectrum_profiles.v2.schema import (
    AccessSection,
    AuthorizationSection,
    DistanceExclusionBinding,
    FixedWidthChannelization,
    GeographySection,
    PowerSection,
    ProfileDocument,
    ProfileMetadata,
    ProfileV2SpectrumDocument,
    ProtectionSection,
    RfSection,
    SpectrumRange,
    SpectrumSection,
    SpectrumSegment,
    TemporalSection,
)
from spectrum_profiles.v2.trust import (
    ProfileLoadProvenance,
    ProfileTrustTier,
    builtin_v2_profiles_dir,
    validate_profile_id,
)

__all__ = [
    "AccessSection",
    "AuthorizationSection",
    "DEFAULT_PROFILE_ID",
    "DistanceExclusionBinding",
    "FixedWidthChannelization",
    "GeographySection",
    "PowerSection",
    "ProfileDoctorFinding",
    "ProfileDoctorReport",
    "ProfileDocument",
    "ProfileLoadProvenance",
    "ProfileMetadata",
    "ProfileTrustTier",
    "ProfileV2SpectrumDocument",
    "ProtectionSection",
    "RfSection",
    "SpectrumRange",
    "SpectrumSection",
    "SpectrumSegment",
    "TemporalSection",
    "active_profile_id",
    "builtin_v2_profiles_dir",
    "canonical_profile_json",
    "canonical_profile_v2_json",
    "diagnose_profile_v2",
    "get_active_profile_document",
    "package_bootstrap_adapter_discovery",
    "package_bootstrap_rf_discovery",
    "parse_profile_document",
    "parse_profile_v2_spectrum",
    "load_profile",
    "load_profile_document",
    "load_profile_document_with_provenance",
    "load_profile_v2",
    "load_profile_v2_document",
    "load_profile_v2_document_with_provenance",
    "load_profile_v2_with_provenance",
    "load_profile_with_provenance",
    "adapters_satisfying_device_capabilities",
    "adapters_satisfying_network_capabilities",
    "negotiate_profile_plugins",
    "primary_spectrum_range",
    "profile_context_from_document",
    "profile_context_from_v2",
    "profile_hash",
    "profile_hash_v2",
    "reload_active_profile_document",
    "render_profile_doctor_report",
    "run_profile_doctor",
    "set_active_profile_document",
    "validate_profile_id",
    "validate_profile_v2_semantics",
]
